# Generated by Django 4.1.5 on 2023-02-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseapp', '0002_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('construction', 'construction'), ('pharmacitical', 'pharmacitical'), ('clothings', 'clothings'), ('jewellery', 'jewellery'), ('sports materials', 'sports materials'), ('Furniture', 'furniture')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
